all: hw_1 hw_2 hw_3 hw_4 hw_5 hw_6 hw_7 hw_8

clean:
	rm -f hw_1.o hw_2.o hw_3.o hw_4.o hw_5.o hw_6.o hw_7.o hw_8.o

hw_1: hw_1.c
	gcc -o hw_1.o hw_1.c -Wall

hw_2: hw_2.c
	gcc -o hw_2.o hw_2.c -Wall

hw_3: hw_3.c
	gcc -o hw_3.o hw_3.c -Wall

hw_4: hw_4.c
	gcc -o hw_4.o hw_4.c -Wall

hw_5: hw_5.c
	gcc -o hw_5.o hw_5.c -Wall

hw_6: hw_6.c
	gcc -o hw_6.o hw_6.c -Wall

hw_7: hw_7.c
	gcc -o hw_7.o hw_7.c -Wall

hw_8: hw_8.c
	gcc -o hw_8.o hw_8.c -Wall
